export const ROUTES = {
  HOME: '/',
  PROFILE: '/profile',
  DETAIL: 'profile/:username',
  UPDATE_PROFILE: '/update_profile',
  LOGIN: '/login',
  BOOK: '/book/:company_name',
  CAR_ROOT: '/car',
  SERVICE: '/service',
  CONTACT: '/contact',
  RULES: '/rules',
  FILLED: '/filled',
  CONFIRM: '/confirm',
  SUCCESS: '/success/:id',
};
